name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

# defaults:
#  run:
#   working-directory: ./docs

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest
    env:
      working-directory: ./docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Deploy
        run: bash docs/tools/deploy.sh